apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: terasecurity-com-tls
spec:
  secretName: terasecurity-com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: terasecurity.com
  # List of domains that this cert is good for
  dnsNames:
    - terasecurity.com
    - www.terasecurity.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - www.terasecurity.com
          - terasecurity.com